### ISSUE TITLE
Abuse of the word "Scalable": This implementation won't scale.

### ISSUE THREAD

**Issue by jnardiello** [IBM/wordpress-sample#28]
Sorry if I sound provocative and aggressive but this implementation won't scale by any mean. Just because it's based on `kubernetes` it doesn't necessarily mean that it will scale.

To be more precise, here you are using `hostPath` as storage. Do you understand that this means that as soon as a pod will be scheduled to a different node, this implementation will break?

I'm just trying to underline that using buzzwords randomly is a bad thing to do. Avoid it.

Regards

**Comment by terrysnyder** [comment]
I'll add to this (disclaimer - newbie experimenting): I did "--replicas=3", but did not get 3 replicas. I got 2 exact replicas (and they do stay in synch as desired), but the third is missing all my custom WordPress files and does not stay in synch (it is not a replica of the first 2). 
Additionally, I can't figure out the that Provider Cloud diagram at the start of readme.md - is there further documentation available to explain it, including the numbers 1 thru 7? It gives me the impression that one of the WordPress instances doesn't connect to the SQL DB, for example...

**Comment by mhmdio** [comment]
I agree this is somehow misleading, we tested using loader.io, and the results were discouraging to use k8s for WP.

**Comment by donnyv12** [comment]
Not to pile on, but I stumbled across this repo because I am trying to solve the same problem of scaling (or achieving HA) of a wordpress site in kubernetes. Ironically, it's a bit easier to deploy MySQL in HA in kubernetes than Wordpress (so far as I can tell), because each replica needs to read and write to the filesystem. Because this tutorial uses a PV and PVC that is `ReadWriteOnce` only one pod can access the PV at a time, making this not a scalable solution.

**Comment by shinebayar-g** [comment]
Description and implementation mismatch.
